### ISSUE TITLE
Multi-Tech Conduit hangs occasionally

### ISSUE THREAD

**Issue by aminran** [kersing/lora_gateway#6]
Hi all,
I am using multitech conduit ip67 gateway in a project. the firmware has been updated to MTCDT AEP 5.0.0 (unsigned) . my app is Nodered but it hangs occasionally. How can i do for this problem?

**Comment by kersing** [comment]
Please use the MultiTech forum for support of their software.

**Comment by aminran** [comment]
I wrote my question in MultiTech forum.
